FROM node:16-alpine 

WORKDIR /app
COPY . .

RUN yarn install
RUN yarn build

ARG API_URL
ENV NODE_ENV production
ENV REACT_APP_PROD_API_URL $API_URL

EXPOSE 3000
CMD [ "yarn", "serve", "-s", "build" ]